#!/bin/bash

_HOME='/home/victor'
_SRC_ROOT='/mnt/snapshot/'
_DEST_ROOT='/mnt/harddrive'

_SCRIPT_DIR="$(cd "${0%/*}"; pwd)"

sudo \
  "${_SCRIPT_DIR}/incremental_backup" "${_HOME}" "${_SRC_ROOT}" "${_DEST_ROOT}"
